top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/mappers
builddir     = /home/jiamin/OSDI/httpd/modules/mappers
VPATH        = /home/jiamin/OSDI/httpd/modules/mappers

include $(top_srcdir)/build/special.mk

