top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/loggers
builddir     = /home/jiamin/OSDI/httpd/modules/loggers
VPATH        = /home/jiamin/OSDI/httpd/modules/loggers

include $(top_srcdir)/build/special.mk

