top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/filters
builddir     = /home/jiamin/OSDI/httpd/modules/filters
VPATH        = /home/jiamin/OSDI/httpd/modules/filters

include $(top_srcdir)/build/special.mk

