top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/aaa
builddir     = /home/jiamin/OSDI/httpd/modules/aaa
VPATH        = /home/jiamin/OSDI/httpd/modules/aaa

include $(top_srcdir)/build/special.mk

