top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/cache
builddir     = /home/jiamin/OSDI/httpd/modules/cache
VPATH        = /home/jiamin/OSDI/httpd/modules/cache

include $(top_srcdir)/build/special.mk

