top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/arch/unix
builddir     = /home/jiamin/OSDI/httpd/modules/arch/unix
VPATH        = /home/jiamin/OSDI/httpd/modules/arch/unix

include $(top_srcdir)/build/special.mk

