top_srcdir   = /home/jiamin/OSDI/httpd
top_builddir = /home/jiamin/OSDI/httpd
srcdir       = /home/jiamin/OSDI/httpd/modules/http
builddir     = /home/jiamin/OSDI/httpd/modules/http
VPATH        = /home/jiamin/OSDI/httpd/modules/http

include $(top_srcdir)/build/special.mk

